@extends('layouts.admin')
@section('title',$customer->name.' - VITA Control')
@push('styles')<link rel="stylesheet" href="{{ asset('css/admin-customer-detail.css') }}">@endpush
@section('content')
@php($confirmed=$registrations->filter(fn($registration) => $registration->status->value === 'CONFIRMED')->count())
<div class="customer-detail-page"><header class="customer-detail-header"><div><a href="{{ route('admin.customers') }}" class="customer-detail-back"><i class="fa-solid fa-arrow-left"></i>Danh sách học viên</a><span class="customer-detail-eyebrow"><i class="fa-solid fa-circle"></i>Hồ sơ học viên</span><h1>{{ $customer->name }}</h1><p>Mã #{{ str_pad((string)$customer->id,4,'0',STR_PAD_LEFT) }} · Tham gia từ {{ $customer->created_at->format('d/m/Y') }}</p></div><a href="{{ route('admin.customers.edit',$customer->id) }}" class="customer-detail-edit"><i class="fa-regular fa-pen-to-square"></i> Chỉnh sửa hồ sơ</a></header>
<div class="customer-detail-layout"><main class="customer-detail-main">
<section class="customer-profile-card"><div class="customer-profile-identity"><span>{{ mb_strtoupper(mb_substr($customer->name,0,1)) }}</span><div><small>Học viên VITA</small><h2>{{ $customer->name }}</h2><p>{{ $customer->gender==='male'?'Nam':($customer->gender==='female'?'Nữ':'Chưa cập nhật giới tính') }}{{ $customer->birthday?' · Sinh ngày '.$customer->birthday->format('d/m/Y'):'' }}</p></div></div><div class="customer-profile-contact"><div><i class="fa-regular fa-envelope"></i><span><small>Email</small><strong>{{ $customer->email }}</strong></span></div><div><i class="fa-solid fa-phone"></i><span><small>Điện thoại</small><strong>{{ $customer->phone }}</strong></span></div><div><i class="fa-solid fa-location-dot"></i><span><small>Địa chỉ</small><strong>{{ $customer->address ?: 'Chưa cập nhật' }}</strong></span></div></div>@if($customer->note)<div class="customer-profile-note"><small>Ghi chú nội bộ</small><p>{{ $customer->note }}</p></div>@endif</section>
<section class="customer-history-card"><div class="customer-history-heading"><span><i class="fa-solid fa-spa"></i></span><div><h2>Lịch sử đăng ký lớp</h2><p>{{ $registrations->count() }} đơn đăng ký trong hệ thống.</p></div></div><div class="customer-registration-list">
@forelse($registrations as $registration)@php($status=$registration->status->value)@php($meta=match($status){'CONFIRMED'=>['Đã duyệt','confirmed','fa-circle-check'],'CANCELLED'=>['Đã hủy','cancelled','fa-circle-xmark'],default=>['Chờ duyệt','pending','fa-clock']})
<article class="customer-registration-row"><span class="customer-registration-icon"><i class="fa-solid fa-spa"></i></span><div class="customer-registration-class"><strong>{{ $registration->class?->name ?? 'Lớp không còn tồn tại' }}</strong><small><i class="fa-solid fa-chalkboard-user"></i>{{ $registration->class?->teacher?->name ?? 'Chưa có giáo viên' }} · {{ $registration->package_months }} tháng</small></div><div class="customer-registration-price"><strong>{{ number_format($registration->final_price,0,',','.') }}đ</strong><small>{{ $registration->created_at->format('d/m/Y') }}</small></div><span class="registration-status registration-status--{{ $meta[1] }}"><i class="fa-regular {{ $meta[2] }}"></i>{{ $meta[0] }}</span><a href="{{ route('admin.registrations.detail',$registration->id) }}" aria-label="Xem đơn #{{ $registration->id }}"><i class="fa-solid fa-chevron-right"></i></a></article>
@empty<div class="customer-history-empty"><span><i class="fa-regular fa-folder-open"></i></span><h3>Chưa có đơn đăng ký</h3><p>Học viên chưa đăng ký lớp Yoga nào.</p></div>@endforelse
</div></section></main>
<aside class="customer-detail-sidebar"><section class="customer-overview"><div><span><i class="fa-regular fa-file-lines"></i></span><p><small>Tổng đăng ký</small><strong>{{ $registrations->count() }}</strong></p></div><div><span><i class="fa-regular fa-circle-check"></i></span><p><small>Đã duyệt</small><strong>{{ $confirmed }}</strong></p></div></section><section class="customer-personal-card"><h2>Thông tin cá nhân</h2><dl><div><dt>Ngày sinh</dt><dd>{{ $customer->birthday?->format('d/m/Y') ?? 'Chưa cập nhật' }}</dd></div><div><dt>Giới tính</dt><dd>{{ $customer->gender==='male'?'Nam':($customer->gender==='female'?'Nữ':'Chưa cập nhật') }}</dd></div><div><dt>Ngày tham gia</dt><dd>{{ $customer->created_at->format('d/m/Y') }}</dd></div><div><dt>Cập nhật gần nhất</dt><dd>{{ $customer->updated_at->format('d/m/Y H:i') }}</dd></div></dl></section><section class="customer-detail-actions"><a href="{{ route('admin.customers.edit',$customer->id) }}"><i class="fa-regular fa-pen-to-square"></i>Chỉnh sửa thông tin</a><form method="POST" action="{{ route('admin.customers.delete',$customer->id) }}" data-confirm-title="Xóa học viên?" data-confirm-message="Hồ sơ #{{ $customer->id }} – {{ $customer->name }} sẽ bị xóa nếu chưa phát sinh đăng ký.">@csrf @method('DELETE')<button><i class="fa-regular fa-trash-can"></i>Xóa học viên</button></form></section></aside>
</div></div>
@endsection
