@extends('layouts.admin')
@section('title','Học viên - VITA Control')
@push('styles')<link rel="stylesheet" href="{{ asset('css/admin-customers.css') }}">@endpush
@section('content')
@php($currentStatus = strtolower((string)request('status')))
@php($baseFilter = array_filter(['search'=>request('search')]))
<div class="customers-page">
    <header class="customers-header"><div><span class="customers-eyebrow"><i class="fa-solid fa-circle"></i> Quản lý cộng đồng</span><h1>Danh sách học viên</h1><p>Theo dõi hồ sơ liên hệ và lịch sử tham gia lớp Yoga.</p></div><a href="{{ route('admin.customers.create') }}" class="customers-create"><i class="fa-solid fa-plus"></i> Thêm học viên</a></header>
    <section class="customers-stats">
        <a href="{{ route('admin.customers',$baseFilter) }}" class="customer-stat {{ $currentStatus===''?'is-active':'' }}"><span><i class="fa-solid fa-users"></i></span><div><small>Tất cả học viên</small><strong>{{ number_format($stats['total']) }}</strong></div></a>
        <a href="{{ route('admin.customers',array_merge($baseFilter,['status'=>'registered'])) }}" class="customer-stat customer-stat--registered {{ $currentStatus==='registered'?'is-active':'' }}"><span><i class="fa-solid fa-spa"></i></span><div><small>Đã có đăng ký</small><strong>{{ number_format($stats['registered']) }}</strong></div></a>
        <a href="{{ route('admin.customers',array_merge($baseFilter,['status'=>'unregistered'])) }}" class="customer-stat customer-stat--empty {{ $currentStatus==='unregistered'?'is-active':'' }}"><span><i class="fa-regular fa-folder-open"></i></span><div><small>Chưa đăng ký</small><strong>{{ number_format($stats['unregistered']) }}</strong></div></a>
        <article class="customer-stat customer-stat--new"><span><i class="fa-solid fa-user-plus"></i></span><div><small>Mới trong tháng</small><strong>{{ number_format($stats['new_this_month']) }}</strong></div></article>
    </section>
    <section class="customers-toolbar"><form method="GET" action="{{ route('admin.customers') }}" class="customers-search">@if($currentStatus)<input type="hidden" name="status" value="{{ $currentStatus }}">@endif<i class="fa-solid fa-magnifying-glass"></i><input type="search" name="search" value="{{ request('search') }}" placeholder="Tên, email, số điện thoại hoặc địa chỉ..." aria-label="Tìm kiếm học viên">@if(request()->filled('search'))<a href="{{ route('admin.customers',array_filter(['status'=>$currentStatus])) }}" aria-label="Xóa tìm kiếm"><i class="fa-solid fa-xmark"></i></a>@endif<button>Tìm kiếm</button></form><div><strong>{{ number_format($customers->total()) }} học viên</strong><small>Trang {{ $customers->currentPage() }}/{{ max(1,$customers->lastPage()) }}</small></div></section>
    <section class="customers-table-panel"><div class="customers-table-wrap"><table class="customers-table"><thead><tr><th>Học viên</th><th>Liên hệ</th><th>Thông tin cá nhân</th><th>Đăng ký lớp</th><th>Ngày tham gia</th><th><span class="sr-only">Thao tác</span></th></tr></thead><tbody>
    @forelse($customers as $customer)
        <tr><td data-label="Học viên"><div class="customer-identity"><span>{{ mb_strtoupper(mb_substr($customer->name,0,1)) }}</span><div><strong>{{ $customer->name }}</strong><small>#{{ str_pad((string)$customer->id,4,'0',STR_PAD_LEFT) }}</small></div></div></td>
        <td data-label="Liên hệ"><div class="customer-contact"><a href="mailto:{{ $customer->email }}"><i class="fa-regular fa-envelope"></i>{{ $customer->email }}</a><a href="tel:{{ $customer->phone }}"><i class="fa-solid fa-phone"></i>{{ $customer->phone }}</a></div></td>
        <td data-label="Cá nhân"><div class="customer-personal"><span><i class="fa-regular fa-calendar"></i>{{ $customer->birthday?->format('d/m/Y') ?? 'Chưa có ngày sinh' }}</span><span><i class="fa-regular fa-user"></i>{{ $customer->gender==='male'?'Nam':($customer->gender==='female'?'Nữ':'Chưa cập nhật') }}</span></div></td>
        <td data-label="Đăng ký"><div class="customer-registration-count {{ $customer->registrations_count ? 'has-registration':'' }}"><strong>{{ $customer->registrations_count }}</strong><span>tổng đơn</span><small>{{ $customer->confirmed_registrations_count }} đã duyệt</small></div></td>
        <td data-label="Tham gia"><div class="customer-created"><strong>{{ $customer->created_at->format('d/m/Y') }}</strong><small>{{ $customer->created_at->format('H:i') }}</small></div></td>
        <td data-label="Thao tác"><div class="customer-actions"><a href="{{ route('admin.customers.detail',$customer->id) }}" class="primary"><i class="fa-regular fa-eye"></i> Chi tiết</a><a href="{{ route('admin.customers.edit',$customer->id) }}" aria-label="Sửa {{ $customer->name }}"><i class="fa-regular fa-pen-to-square"></i></a><form method="POST" action="{{ route('admin.customers.delete',$customer->id) }}" data-confirm-title="Xóa học viên?" data-confirm-message="Hồ sơ #{{ $customer->id }} – {{ $customer->name }} sẽ bị xóa nếu chưa phát sinh đăng ký.">@csrf @method('DELETE')<button aria-label="Xóa {{ $customer->name }}"><i class="fa-regular fa-trash-can"></i></button></form></div></td></tr>
    @empty<tr><td colspan="6"><div class="customers-empty"><span><i class="fa-solid fa-users"></i></span><h2>Không tìm thấy học viên</h2><p>Thử thay đổi từ khóa hoặc bộ lọc đang dùng.</p><a href="{{ request()->hasAny(['search','status'])?route('admin.customers'):route('admin.customers.create') }}">{{ request()->hasAny(['search','status'])?'Xóa bộ lọc':'Thêm học viên đầu tiên' }}</a></div></td></tr>@endforelse
    </tbody></table></div>
    @if($customers->hasPages())<nav class="customers-pagination">@if($customers->onFirstPage())<span class="disabled"><i class="fa-solid fa-arrow-left"></i> Trang trước</span>@else<a href="{{ $customers->previousPageUrl() }}"><i class="fa-solid fa-arrow-left"></i> Trang trước</a>@endif<span>{{ $customers->currentPage() }}/{{ $customers->lastPage() }}</span>@if($customers->hasMorePages())<a href="{{ $customers->nextPageUrl() }}">Trang sau <i class="fa-solid fa-arrow-right"></i></a>@else<span class="disabled">Trang sau <i class="fa-solid fa-arrow-right"></i></span>@endif</nav>@endif</section>
</div>
@endsection
