@extends('layouts.admin')
@section('title','Giáo viên - VITA Control')
@push('styles')<link rel="stylesheet" href="{{ asset('css/admin-teachers.css') }}"><link rel="stylesheet" href="{{ asset('css/admin-teachers-search.css') }}">@endpush
@section('content')
@php($currentStatus=strtolower((string)request('status'))) @php($baseFilter=array_filter(['search'=>request('search')]))
<div class="teachers-page"><header class="teachers-header"><div><span class="teachers-eyebrow"><i class="fa-solid fa-circle"></i>Đội ngũ chuyên môn</span><h1>Danh sách giáo viên</h1><p>Quản lý hồ sơ chuyên môn, tài khoản và các lớp Yoga phụ trách.</p></div><a href="{{ route('admin.teachers.create') }}" class="teachers-create"><i class="fa-solid fa-plus"></i>Thêm giáo viên</a></header>
<section class="teachers-stats"><a href="{{ route('admin.teachers',$baseFilter) }}" class="teacher-stat {{ $currentStatus===''?'active':'' }}"><span><i class="fa-solid fa-chalkboard-user"></i></span><div><small>Tất cả giáo viên</small><strong>{{ $stats['total'] }}</strong></div></a><a href="{{ route('admin.teachers',array_merge($baseFilter,['status'=>'assigned'])) }}" class="teacher-stat {{ $currentStatus==='assigned'?'active':'' }}"><span><i class="fa-solid fa-spa"></i></span><div><small>Đã phân lớp</small><strong>{{ $stats['assigned'] }}</strong></div></a><a href="{{ route('admin.teachers',array_merge($baseFilter,['status'=>'unassigned'])) }}" class="teacher-stat {{ $currentStatus==='unassigned'?'active':'' }}"><span><i class="fa-regular fa-calendar-xmark"></i></span><div><small>Chưa phân lớp</small><strong>{{ $stats['unassigned'] }}</strong></div></a><article class="teacher-stat"><span><i class="fa-solid fa-user-plus"></i></span><div><small>Mới trong tháng</small><strong>{{ $stats['new_this_month'] }}</strong></div></article></section>
<section class="teachers-toolbar"><form method="GET" action="{{ route('admin.teachers') }}">@if($currentStatus)<input type="hidden" name="status" value="{{ $currentStatus }}">@endif<i class="fa-solid fa-magnifying-glass"></i><input type="search" name="search" value="{{ request('search') }}" placeholder="Tên, email, số điện thoại hoặc kinh nghiệm...">@if(request()->filled('search'))<a href="{{ route('admin.teachers',array_filter(['status'=>$currentStatus])) }}"><i class="fa-solid fa-xmark"></i></a>@endif<button>Tìm kiếm</button></form><div><strong>{{ $teachers->total() }} giáo viên</strong><small>Trang {{ $teachers->currentPage() }}/{{ max(1,$teachers->lastPage()) }}</small></div></section>
<section class="teachers-grid">@forelse($teachers as $teacher)@php($hasAvatar=$teacher->avatar&&file_exists(public_path('storage/'.$teacher->avatar)))
<article class="teacher-card"><header><div class="teacher-avatar">@if($hasAvatar)<img src="{{ asset('storage/'.$teacher->avatar) }}" alt="Ảnh {{ $teacher->name }}">@else<span>{{ mb_strtoupper(mb_substr($teacher->name,0,1)) }}</span>@endif</div><div><small>#{{ str_pad((string)$teacher->id,3,'0',STR_PAD_LEFT) }}</small><h2>{{ $teacher->name }}</h2><span><i class="fa-solid fa-award"></i>{{ $teacher->exp_year }} năm kinh nghiệm</span></div><span class="teacher-account {{ $teacher->user?'enabled':'disabled' }}"><i class="fa-solid {{ $teacher->user?'fa-user-check':'fa-user-slash' }}"></i>{{ $teacher->user?'Có tài khoản':'Chưa có tài khoản' }}</span></header><p class="teacher-description">{{ Str::limit($teacher->description,115) }}</p><div class="teacher-contact"><span><i class="fa-regular fa-envelope"></i>{{ $teacher->email }}</span><span><i class="fa-solid fa-phone"></i>{{ $teacher->phone }}</span></div><div class="teacher-class-stats"><div><small>Tổng số lớp</small><strong>{{ $teacher->classes_count }}</strong></div><div><small>Đang/Sắp dạy</small><strong>{{ $teacher->active_classes_count }}</strong></div><div><small>Gia nhập</small><strong>{{ $teacher->created_at->format('d/m/Y') }}</strong></div></div><footer><a href="{{ route('admin.teachers.detail',$teacher->id) }}" class="primary"><i class="fa-regular fa-eye"></i>Chi tiết</a><a href="{{ route('admin.teachers.edit',$teacher->id) }}"><i class="fa-regular fa-pen-to-square"></i></a><form method="POST" action="{{ route('admin.teachers.delete',$teacher->id) }}" data-confirm-title="Xóa giáo viên?" data-confirm-message="Giáo viên #{{ $teacher->id }} – {{ $teacher->name }} sẽ bị xóa nếu chưa được phân lớp.">@csrf @method('DELETE')<button aria-label="Xóa {{ $teacher->name }}"><i class="fa-regular fa-trash-can"></i></button></form></footer></article>
@empty<div class="teachers-empty"><span><i class="fa-solid fa-chalkboard-user"></i></span><h2>Không tìm thấy giáo viên</h2><p>Thử thay đổi từ khóa hoặc bộ lọc.</p><a href="{{ request()->hasAny(['search','status'])?route('admin.teachers'):route('admin.teachers.create') }}">{{ request()->hasAny(['search','status'])?'Xóa bộ lọc':'Thêm giáo viên đầu tiên' }}</a></div>@endforelse</section>
@if($teachers->hasPages())<nav class="teachers-pagination">@if($teachers->onFirstPage())<span class="disabled">← Trang trước</span>@else<a href="{{ $teachers->previousPageUrl() }}">← Trang trước</a>@endif<span>{{ $teachers->currentPage() }}/{{ $teachers->lastPage() }}</span>@if($teachers->hasMorePages())<a href="{{ $teachers->nextPageUrl() }}">Trang sau →</a>@else<span class="disabled">Trang sau →</span>@endif</nav>@endif</div>
@endsection
