@extends('layouts.admin')
@section('title',$teacher->name.' - VITA Control')
@push('styles')<link rel="stylesheet" href="{{ asset('css/admin-teacher-detail.css') }}">@endpush
@section('content')
@php($hasAvatar=$teacher->avatar&&file_exists(public_path('storage/'.$teacher->avatar))) @php($activeClasses=$classes->filter(fn($class)=>$class->end_date->gte(today()))->count()) @php($totalStudents=$classes->sum('confirmed_registrations_count'))
<div class="teacher-detail-page"><header class="teacher-detail-header"><div><a href="{{ route('admin.teachers') }}" class="teacher-detail-back"><i class="fa-solid fa-arrow-left"></i>Danh sách giáo viên</a><span class="teacher-detail-eyebrow"><i class="fa-solid fa-circle"></i>Hồ sơ chuyên môn</span><h1>{{ $teacher->name }}</h1><p>Mã #{{ str_pad((string)$teacher->id,3,'0',STR_PAD_LEFT) }} · {{ $teacher->exp_year }} năm kinh nghiệm</p></div><a href="{{ route('admin.teachers.edit',$teacher->id) }}" class="teacher-detail-edit"><i class="fa-regular fa-pen-to-square"></i>Chỉnh sửa hồ sơ</a></header>
<section class="teacher-detail-hero"><div class="teacher-detail-avatar">@if($hasAvatar)<img src="{{ asset('storage/'.$teacher->avatar) }}" alt="Ảnh {{ $teacher->name }}">@else<span>{{ mb_strtoupper(mb_substr($teacher->name,0,1)) }}</span>@endif</div><div class="teacher-detail-intro"><span>Giáo viên Yoga tại VITA</span><h2>{{ $teacher->name }}</h2><p>{{ $teacher->description }}</p></div><div class="teacher-detail-badges"><span><i class="fa-solid fa-award"></i>{{ $teacher->exp_year }} năm kinh nghiệm</span><span class="{{ $teacher->user?'enabled':'disabled' }}"><i class="fa-solid {{ $teacher->user?'fa-user-check':'fa-user-slash' }}"></i>{{ $teacher->user?'Tài khoản hoạt động':'Chưa có tài khoản' }}</span></div></section>
<div class="teacher-detail-layout"><main class="teacher-detail-main"><section class="teacher-classes-card"><div class="teacher-section-heading"><span><i class="fa-solid fa-spa"></i></span><div><h2>Các lớp phụ trách</h2><p>{{ $classes->count() }} lớp được phân công cho giáo viên.</p></div></div><div class="teacher-class-list">@forelse($classes as $class)@php($phase=today()->lt($class->start_date)?['Sắp diễn ra','upcoming']:(today()->gt($class->end_date)?['Đã kết thúc','ended']:['Đang diễn ra','ongoing']))<article><span class="teacher-class-icon"><i class="fa-solid fa-spa"></i></span><div class="teacher-class-main"><div><strong>{{ $class->name }}</strong><span class="phase {{ $phase[1] }}">{{ $phase[0] }}</span></div><small><i class="fa-regular fa-calendar"></i>{{ $class->lich_hoc }} · {{ $class->start_time->format('H:i') }}–{{ $class->end_time->format('H:i') }} · <i class="fa-solid fa-location-dot"></i>{{ $class->location }}</small></div><div class="teacher-class-capacity"><strong>{{ $class->confirmed_registrations_count }}/{{ $class->quantity }}</strong><small>học viên</small></div><a href="{{ route('admin.classes.detail',$class->id) }}"><i class="fa-solid fa-chevron-right"></i></a></article>@empty<div class="teacher-classes-empty"><span><i class="fa-regular fa-calendar-xmark"></i></span><h3>Chưa được phân lớp</h3><p>Giáo viên chưa phụ trách lớp Yoga nào.</p></div>@endforelse</div></section></main>
<aside class="teacher-detail-sidebar"><section class="teacher-overview"><div><small>Tổng số lớp</small><strong>{{ $classes->count() }}</strong></div><div><small>Đang/Sắp dạy</small><strong>{{ $activeClasses }}</strong></div><div><small>Tổng học viên</small><strong>{{ $totalStudents }}</strong></div></section><section class="teacher-contact-card"><h2>Thông tin liên hệ</h2><dl><div><dt>Email đăng nhập</dt><dd>{{ $teacher->email }}</dd></div><div><dt>Số điện thoại</dt><dd>{{ $teacher->phone }}</dd></div><div><dt>Ngày sinh</dt><dd>{{ $teacher->birthday->format('d/m/Y') }}</dd></div><div><dt>Ngày gia nhập</dt><dd>{{ $teacher->created_at->format('d/m/Y') }}</dd></div></dl></section><section class="teacher-detail-actions"><a href="{{ route('admin.teachers.edit',$teacher->id) }}"><i class="fa-regular fa-pen-to-square"></i>Chỉnh sửa hồ sơ</a><form method="POST" action="{{ route('admin.teachers.delete',$teacher->id) }}" data-confirm-title="Xóa giáo viên?" data-confirm-message="Giáo viên #{{ $teacher->id }} – {{ $teacher->name }} sẽ bị xóa nếu chưa được phân lớp.">@csrf @method('DELETE')<button><i class="fa-regular fa-trash-can"></i>Xóa giáo viên</button></form></section></aside></div></div>
@endsection
