<div class="customer-form-page">
<header class="customer-form-header"><div><a href="{{ $cancelRoute }}" class="customer-form-back"><i class="fa-solid fa-arrow-left"></i>{{ $isEdit?'Chi tiết học viên':'Danh sách học viên' }}</a><span class="customer-form-eyebrow"><i class="fa-solid fa-circle"></i>{{ $isEdit?'Cập nhật hồ sơ':'Hồ sơ mới' }}</span><h1>{{ $isEdit?'Chỉnh sửa học viên':'Thêm học viên mới' }}</h1><p>{{ $isEdit?'Cập nhật thông tin liên hệ và ghi chú cho '.$customer->name.'.':'Tạo hồ sơ học viên trước khi đăng ký lớp Yoga.' }}</p></div>@if($isEdit)<div class="customer-form-meta"><span>{{ mb_strtoupper(mb_substr($customer->name,0,1)) }}</span><div><strong>{{ $customer->name }}</strong><small>Mã học viên #{{ str_pad((string)$customer->id,4,'0',STR_PAD_LEFT) }}</small></div></div>@endif</header>
<form id="adminCustomerForm" class="customer-form-layout" method="POST" action="{{ $formAction }}">@csrf @if($isEdit)@method('PUT')@endif
<main class="customer-form-main">
<section class="customer-form-card"><div class="customer-form-card__header"><span>01</span><div><h2>Thông tin liên hệ</h2><p>Dùng để nhận diện và liên hệ trực tiếp với học viên.</p></div></div><div class="customer-field-grid">
<div class="customer-field customer-field--full"><label for="name">Họ và tên <b>*</b></label><div class="customer-input"><i class="fa-regular fa-user"></i><input id="name" name="name" value="{{ old('name',$customer?->name) }}" maxlength="100" placeholder="Ví dụ: Nguyễn Minh Anh" required autofocus></div>@error('name')<small class="error">{{ $message }}</small>@enderror</div>
<div class="customer-field"><label for="email">Email <b>*</b>@if($isEdit)<span class="customer-locked-label"><i class="fa-solid fa-lock"></i> Không thể thay đổi</span>@endif</label><div class="customer-input"><i class="fa-regular fa-envelope"></i><input type="email" id="email" name="email" value="{{ old('email',$customer?->email) }}" maxlength="100" placeholder="minhanh@email.com" {{ $isEdit ? 'readonly aria-describedby=emailLockedHelp' : '' }} required></div>@if($isEdit)<small id="emailLockedHelp" class="customer-field-help">Email được dùng để đăng nhập nên không thể chỉnh sửa.</small>@endif @error('email')<small class="error">{{ $message }}</small>@enderror</div>
<div class="customer-field"><label for="phone">Số điện thoại <b>*</b></label><div class="customer-input"><i class="fa-solid fa-phone"></i><input type="tel" id="phone" name="phone" value="{{ old('phone',$customer?->phone) }}" maxlength="20" placeholder="090 123 4567" required></div>@error('phone')<small class="error">{{ $message }}</small>@enderror</div>
</div></section>
<section class="customer-form-card"><div class="customer-form-card__header"><span>02</span><div><h2>Thông tin cá nhân</h2><p>Thông tin bổ sung giúp chăm sóc học viên phù hợp hơn.</p></div></div><div class="customer-field-grid">
<div class="customer-field"><label for="birthday">Ngày sinh <small>Không bắt buộc</small></label><input type="date" id="birthday" name="birthday" max="{{ today()->format('Y-m-d') }}" value="{{ old('birthday',$customer?->birthday?->format('Y-m-d')) }}">@error('birthday')<small class="error">{{ $message }}</small>@enderror</div>
<div class="customer-field"><label for="gender">Giới tính <small>Không bắt buộc</small></label><select id="gender" name="gender"><option value="">Chưa cập nhật</option><option value="male" {{ old('gender',$customer?->gender)==='male'?'selected':'' }}>Nam</option><option value="female" {{ old('gender',$customer?->gender)==='female'?'selected':'' }}>Nữ</option></select>@error('gender')<small class="error">{{ $message }}</small>@enderror</div>
<div class="customer-field customer-field--full"><label for="address">Địa chỉ <small>Không bắt buộc</small></label><div class="customer-input"><i class="fa-solid fa-location-dot"></i><input id="address" name="address" value="{{ old('address',$customer?->address) }}" maxlength="255" placeholder="Số nhà, đường, quận/huyện, tỉnh/thành"></div>@error('address')<small class="error">{{ $message }}</small>@enderror</div>
</div></section>
<section class="customer-form-card"><div class="customer-form-card__header"><span>03</span><div><h2>Ghi chú nội bộ</h2><p>Lưu nhu cầu tập luyện hoặc thông tin cần lưu ý.</p></div></div><div class="customer-field"><label for="note">Ghi chú <small>Không bắt buộc</small></label><textarea id="note" name="note" maxlength="255" rows="5" placeholder="Ví dụ: Cần tránh động tác gây áp lực lên đầu gối...">{{ old('note',$customer?->note) }}</textarea><div class="customer-field-meta"><span>Chỉ quản trị viên nhìn thấy</span><span id="customerNoteCounter">0/255</span></div>@error('note')<small class="error">{{ $message }}</small>@enderror</div></section>
</main>
<aside class="customer-form-preview"><div class="customer-preview-heading"><span><i class="fa-regular fa-id-card"></i></span><div><h2>Xem trước hồ sơ</h2><p>Cập nhật theo nội dung đang nhập.</p></div></div><div class="customer-preview-profile"><span id="previewCustomerInitial">H</span><h3 id="previewCustomerName">Tên học viên</h3><small id="previewCustomerMeta">Chưa cập nhật thông tin cá nhân</small></div><dl><div><dt><i class="fa-regular fa-envelope"></i>Email</dt><dd id="previewCustomerEmail">Chưa cập nhật</dd></div><div><dt><i class="fa-solid fa-phone"></i>Điện thoại</dt><dd id="previewCustomerPhone">Chưa cập nhật</dd></div><div><dt><i class="fa-solid fa-location-dot"></i>Địa chỉ</dt><dd id="previewCustomerAddress">Chưa cập nhật</dd></div></dl><div class="customer-form-notice"><i class="fa-solid fa-shield-halved"></i><p><strong>Thông tin riêng tư</strong><span>Chỉ sử dụng dữ liệu học viên cho vận hành và chăm sóc tại VITA.</span></p></div><button class="customer-form-submit"><span>{{ $isEdit?'Lưu thay đổi':'Tạo học viên' }}</span><i class="fa-solid fa-arrow-right"></i></button><a href="{{ $cancelRoute }}" class="customer-form-cancel">Hủy và quay lại</a></aside>
</form></div>
